[package]
name = "game_of_life"
version = "0.1.0"
edition = "2018"
authors = ["SULAPIS <sulapis@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.20.0"
rand="0.8.4"